### PR TITLE
Removing unused docker volumes

### PR DESCRIPTION
**Pull request by franciscofsales**
this only works for docker v1.9+

### CODE REVIEW

**Comment by cusspvz** [comment]
Seems that we have to insert a version checker for this to work

**Comment by franciscofsales** [comment]
yeah.. that and the docs... i'll handle it

**Comment by franciscofsales** [comment]
@cusspvz docker v1.9 is from 2015... not sure that check is needed anymore..thoughts?

**Comment by franciscofsales** [comment]
bump

**Pull request merged**
